### ISSUE TITLE
Request access for Spotify

### ISSUE THREAD

**Issue by dzolotusky** [cncf/tab#1]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name:
Spotify

Github usernames:
1. dzolotusky
2.
...

Email addresses:
1. dzolo@spotify.com
2.
...

**Comment by oicheryl** [comment]
Sent invitation!

**Comment by dzolotusky** [comment]
Can you please add:
GitHub:
tomaslundborg
stefanalund


Email:
lundborg@spotify.com
alund@spotify.com
