### ISSUE TITLE
Request access for Zalando [DRAFT]

### ISSUE THREAD

**Issue by hjacobs** [cncf/tab#10]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: Zalando SE

Github usernames:
1. [hpdang](https://github.com/hpdang)
2. [mikkeloscar](https://github.com/mikkeloscar)
3. [krgr](https://github.com/krgr)
4. [jrake-revelant](https://github.com/jrake-revelant)

Email addresses:
1. hong.dang@zalando.de
2. mikkel.larsen@zalando.de
3. tim.kroeger@zalando.de
4. jannis.rake-revelant@zalando.de

**Comment by hjacobs** [comment]
@oicheryl I will collect more colleagues to add, so no need to process this just yet.

**Comment by caniszczyk** [comment]
anything else here @oicheryl

**Comment by oicheryl** [comment]
@hjacobs any more colleagues to add?

**Comment by hjacobs** [comment]
@oicheryl I now added a batch of people (some might already have access). Thanks!

**Comment by oicheryl** [comment]
I've sent invitations to all of them. Thanks!
