### ISSUE TITLE
Request access for Workday

### ISSUE THREAD

**Issue by djdoran01** [cncf/tab#11]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: Workday

Github usernames:
1. djdoran01
2.
...

Email addresses:
1. dave.doran@workday.com
2.
...

**Comment by oicheryl** [comment]
I've sent an invitation for the endusers repo, and you should receive the mailing list/calendar invitations soon.

Thanks!
