### ISSUE TITLE
Request access for [ORGANIZATION NAME]

### ISSUE THREAD

**Issue by JiyeYu** [cncf/tab#13]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name:
Hitachi, Ltd. Research & Development Group
Github usernames:
1. JiyeYu
2.
...

Email addresses:
1. troyspur@gmail.com
2.
...

**Comment by oicheryl** [comment]
Hi @JiyeYu, Hitachi is not a member of the end user community so is not eligible for access to the private repo. Thanks for your interest!
