### ISSUE TITLE
Request access for Groupon

### ISSUE THREAD

**Issue by jonpliske** [cncf/tab#14]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: Groupon

Github usernames:
1. jonpliske
2.
...

Email addresses:
1. jpliske@groupon.com
2.
...

**Comment by oicheryl** [comment]
Done. Thanks!
