### ISSUE TITLE
Request access for [Zendesk]

### ISSUE THREAD

**Issue by aymen-chetoui** [cncf/tab#15]
Vincenzo and I don't have access to the private repo https://github.com/cncf/enduser

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: Zendesk

Github usernames:
1. aymen-chetoui
2. vvicaretti

Email addresses:
1. achetoui@zendesk.com
2. vvicaretti@zendesk.com

**Comment by oicheryl** [comment]
Done, thanks!
