### ISSUE TITLE
Request access for Mobiliar

### ISSUE THREAD

**Issue by sandowm** [cncf/tab#17]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: Swiss Mobiliar Insurance

Github usernames:
1. sandowm
2. Philogros
3. schafei
4. aymonc
5. johnhowlett
6. sybnex

Email addresses:
1. malte+cncf@sandow.cc
2. philipp.grossenbacher@mobi.ch
3. iwan.schafer@mobi.ch
4. caymon@gmx.net
5. johnhowlett@gmx.ch
6. sybnex@gmail.com

**Comment by oicheryl** [comment]
I've added you all to the Github repo and to the mailing list.

Taylor can add you to the calendar invitations and Slack, but she's away this week. I'll nudge her next week.

**Comment by taylorwaggoner** [comment]
I've added everyone to the meetings and Slack.  Thanks!
