### ISSUE TITLE
Request access for Indeed.com

### ISSUE THREAD

**Issue by mjpitz** [cncf/tab#18]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: Indeed.com

Github usernames:
1. mjpitz

Work email addresses (we don't use personal email addresses for this group):
1. mjpitz@indeed.com

**Comment by oicheryl** [comment]
Sent you an invitation. Thanks!
