### ISSUE TITLE
Request access for curve

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [cncf/tab#2]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name:
Curve

Github usernames:
1. (we don't use it, we use bitbucket).

Email addresses:
1. matthew.boyle@imaginecurve.com
2. cto@imaginecurve.com

**Comment by oicheryl** [comment]
Sent invitation!
