### ISSUE TITLE
Request access for [SIG-DX folder in CNCF End User git repo]

### ISSUE THREAD

**Issue by Kin6HA** [cncf/tab#21]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name:

Github usernames:
1.Kin6HA
2.
...

Work email addresses (we don't use personal email addresses for this group):
1.ltk666@ha.org.hk
2.
...

**Comment by oicheryl** [comment]
You've been added. Thanks!
