### ISSUE TITLE
Request access for Meltwater to Slack

### ISSUE THREAD

**Issue by Solisol** [cncf/tab#22]
Submit this issue to request access to the End User Community

* #enduser Slack channel
* --Private repo (https://github.com/cncf/enduser)-- (We already got access to this)
* --Mailing list and meeting invitations-- (We already got access to this)

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: Meltwater

Slack handles and member ID for CNCF slack:
1. Jessica Andersson UJVTPTFR9
2. Federico Hernandez UM284H127
3. Simone Sciarrati UKLGV5B5F

Let me know if you need any additional information!

**Comment by oicheryl** [comment]
I've added Jessica and Federico to end user Slack, Simone is already a member.

Apologies for the delay!
