### ISSUE TITLE
Request access for Spotify

### ISSUE THREAD

**Issue by pianilsson** [cncf/tab#23]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name:
Spotify

Github usernames:
1. pianilsson
2.
...

Work email addresses (we don't use personal email addresses for this group):
1. pia@spotify.com
2.
...

**Comment by oicheryl** [comment]
Sent Github invite, you should already be on the mailing list and events. Thanks!

**Comment by pianilsson** [comment]
Awesome thanks, now I'm in :)

Den mån 2 sep. 2019 kl 18:47 skrev Cheryl Hung <notifications@github.com>:
