### ISSUE TITLE
Request access for Zalando / Arjun & Sergey

### ISSUE THREAD

**Issue by hjacobs** [cncf/tab#24]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: Zalando SE

Github usernames:
1. @arjunrn
2. @nolar

Work email addresses (we don't use personal email addresses for this group):
1. arjun.naik@zalando.de
2. sergey.vasilyev@zalando.de

Both go to KubeCon and could participate at the End User Partner Summit :smile:

**Comment by hjacobs** [comment]
@oicheryl ping :smile:

**Comment by oicheryl** [comment]
Github done, emails will be processed today. Thanks for the reminder @hjacobs!
