### ISSUE TITLE
Request access for Entegral

### ISSUE THREAD

**Issue by robertvoliva** [cncf/tab#26]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name:
Entegral

Github usernames:
1.  robertvoliva
2.  brandentimm

Work email addresses (we don't use personal email addresses for this group):
1.  rvoliva@entegral.com
2.  btimm@entegral.com

**Comment by oicheryl** [comment]
I've sent you invitations to the Github repo. Thanks!

**Comment by oicheryl** [comment]
Also, we've just launched http://memberdesk.cncf.io, so you also can file future requests there.

**Comment by taylorwaggoner** [comment]
I've sent invitations to the end user meetings and mailing list
