### ISSUE TITLE
Request access for Spotify

### ISSUE THREAD

**Issue by RochesterinNYC** [cncf/tab#31]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: Spotify

Github usernames:
1. rochesterinnyc
...

Work email addresses (we don't use personal email addresses for this group):
1. jameswen@spotify.com
...

I don't know what the login would be for trying to request access via https://cncfservicedesk.atlassian.net/servicedesk/customer/user/login?destination=portals, so hence this Github issue.

**Comment by RochesterinNYC** [comment]
@oicheryl could I get access please?

**Comment by oicheryl** [comment]
Done. The primary contact should have access to that link, so Dave Z for Spotify.
