### ISSUE TITLE
community changelog for end users

### ISSUE THREAD

**Issue by parispittman** [cncf/tab#37]
problem:
end users and the rest of the ecosystem need to hear about deprecations, major releases, security incidents, etc. in a high level summary about all cloud native projects. its more than difficult to keep track of each project in Some Kind of usage and these areas are some of the most important. 

possible solution:
some kind of community changelog on the cloud native site that folks can subscribe to
also boosted at the end user sig

**Comment by onlydole** [comment]
This is a great idea, @parispittman! I think most of these contexts can be surfaced from GitHub, and I am curious to hear from teams on how they track deprecations and other updates.

**Comment by MylesBorins** [comment]
If you had a centralized repository that used PRs to track project wide changes you could use auto-generated release notes + configured categories to create a roll up as requested above

https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options

**Comment by onlydole** [comment]
Closing this based on the feedback in https://github.com/cncf/foundation/issues/348
