### ISSUE TITLE
Reference Architecture: CERN

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/tab#39]
Write down the reference architecture for CERN.

The initial version follows the [questionnaire template](https://docs.google.com/document/d/1vC03JQ65UXCDAkHFPOG2SBPgU5gqS_w-gdrMfStm_Qw/edit?usp=sharing) defined by the CNCF Research User Group (RUG).

Once that is filled in, the final document for the TAB can be created.

Current WIP version is  [available here](https://docs.google.com/document/d/1CUFrC-c8mrTnLqf14KuRetqHDpDMxF5T4X8iBmTelu0/edit?usp=sharing).

**Comment by rochaporto** [comment]
Dupe https://github.com/cncf/tab/issues/43
