### ISSUE TITLE
Request access for Credit Suisse

### ISSUE THREAD

**Issue by CSHammer** [cncf/tab#4]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: Credit Suisse

Github usernames:
1. CSHammer
2.
...

Email addresses:
1. michael.hammer@credit-suisse.com
2.
...

**Comment by oicheryl** [comment]
Sent invitation!
