### ISSUE TITLE
Request access for PostFinance

### ISSUE THREAD

**Issue by imathu** [cncf/tab#6]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name:

Github usernames:
1. imathu
2. zbindenren

Email addresses:
1. mathias.herzog@postfinance.ch
2. rene.zbinden@postfinance.ch

**Comment by oicheryl** [comment]
Sent invitation!
