### ISSUE TITLE
Request access for NASDAQ

### ISSUE THREAD

**Issue by techthumb** [cncf/tab#7]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: NASDAQ

Github usernames:
1. @techthumb

Email addresses:
1. kunal.parikh@nasdaq.com

**Comment by oicheryl** [comment]
Invited!
