### ISSUE TITLE
Request access for Zalando

### ISSUE THREAD

**Issue by gkoutav** [cncf/tab#8]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name:

Github usernames:
1. https://github.com/gkoutav
2.
...

Email addresses:
1. vasiliki.gkouta@zalando.de
2.
...

**Comment by oicheryl** [comment]
Invited!
